### ISSUE TITLE
Input directory layout is ignored in output

### ISSUE THREAD

**Issue by o-nix** [trajano/batik-maven-plugin#1]
So, having mainDir > (dir1 > file1.svg) + (dir2 > file2.svg) I'm getting the output like outDir > (file1.png + file2.png). Looks like a problem of [this](https://github.com/trajano/batik-maven-plugin/blob/master/src/main/java/net/trajano/mojo/batik/RasterizerMojo.java#L165) line outside of an output loop.

**Comment by trajano** [comment]
Do you have a pom file that demonstrates this?

**Comment by trajano** [comment]
Closed due to inactivity

**Comment by catkeeper1** [comment]
I got the same issue. My pom file is:
`<plugin>
                <groupId>net.trajano.mojo</groupId>
                <artifactId>batik-maven-plugin</artifactId>
                <version>1.1.1</version>
                <configuration>
                    <destDir>${basedir}/target/generated-resources/batik/</destDir>
                    <mimeType>image/png</mimeType>
                    <svgResources>
                        <resource>
                            <directory>${basedir}/target/site/apidocs</directory>
                            <filtering>false</filtering>
                            <includes>
                                <include>**/doc-files/*.svg</include>
                            </includes>
                        </resource>
                    </svgResources>
                </configuration>
</plugin>`
Actually, there are many svg files under different folder in ${basedir}/target/site/apidocs. After the convertion, all converted files are under ${basedir}/target/generated-resources/batik/ directly. I hope
the folder structure in input can be kept. Any idea?
